default_platform(:ios)

APP_APPLE_ID = ENV["APP_APPLE_ID"]
BUNDLE_ID = ENV["BUNDLE_ID"]
PROVISIONING_PROFILE_SPECIFIER = ENV["PROVISIONING_PROFILE_SPECIFIER"]
TEMP_KEYCHAIN_USER = ENV["TEMP_KEYCHAIN_USER"]
TEMP_KEYCHAIN_PASSWORD = ENV["TEMP_KEYCHAIN_PASSWORD"]
GIT_AUTHORIZATION = ENV["GIT_AUTHORIZATION"]

def delete_temp_keychain(name)
  delete_keychain(
    name: name
  ) if File.exist? File.expand_path("~/Library/Keychains/#{name}-db")
end

def create_temp_keychain(name, password)
  create_keychain(
    name: name,
    password: password,
    unlock: false,
    timeout: 0
  )
end

def ensure_temp_keychain(name, password)
  delete_temp_keychain(name)
  create_temp_keychain(name, password)
end

def checkcodesigncerts(name)
  sh('security', 'find-identity', '-v', '-p', 'codesigning')
end

platform :ios do
  lane :build_release do
    keychain_name = TEMP_KEYCHAIN_USER
    keychain_password = TEMP_KEYCHAIN_PASSWORD
    ensure_temp_keychain(keychain_name, keychain_password)

    api_key = app_store_connect_api_key()

    cocoapods(
      clean_install: true
    )

    Dir.chdir "../.." do
      sh("flutter", "config", "--no-analytics")
      sh("flutter", "pub", "get") #Get latest libs
      sh("flutter", "build", "ios", "--release", "--no-codesign")  #Call Flutter Build
    end

    increment_build_number(
      xcodeproj: "Runner.xcodeproj",
      version_number: flutter_version()["version_number"]
      )

    increment_build_number(
      xcodeproj: "Runner.xcodeproj",
      build_number: flutter_version()["version_code"]
    )
    
    match(
      type: 'appstore',
      app_identifier: "#{BUNDLE_ID}",
      git_basic_authorization: Base64.strict_encode64(GIT_AUTHORIZATION),
      readonly: true,
      keychain_name: keychain_name,
      keychain_password: keychain_password,
      api_key: api_key
    )

    checkcodesigncerts(keychain_name)

    gym(
      configuration: "Release",
      workspace: "Runner.xcworkspace",
      scheme: "Runner"
    )
  end

  lane :internal_deploy do
    api_key = app_store_connect_api_key()

    changelog_from_git_commits
    
    pilot(
      apple_id: "#{APP_APPLE_ID}",
      app_identifier: "#{BUNDLE_ID}",
      skip_waiting_for_build_processing: true,
      skip_submission: true,
      distribute_external: false,
      notify_external_testers: false,
      ipa: "./Runner.ipa"
    )
  end

  lane :cleanup do
    delete_temp_keychain(keychain_name)
  end
end
