# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Build a release version"
  lane :build_release do
    Dir.chdir "../.." do
      sh("flutter", "pub", "get") #Get latest libs
      sh("flutter", "build", "appbundle", "--release")  #Call Flutter Build
    end
    gradle(
      task: "bundle",
      build_type: 'Release'
    )
  end

  desc "Deploy a internal version to Google Play"
  lane :internal_deploy do
    validate_play_store_json_key(
      json_key: ENV["ANDROID_PLAYSTORE_CONFIG_JSON_FILENAME"]
    )
    changelog_from_git_commits
    supply(
      track: "internal", 
      aab:"../build/app/outputs/bundle/release/app-release.aab",
      version_code: flutter_version()["version_code"],
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      skip_upload_apk: true,
	    release_status: 'draft'
    )
  end
end
