
name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_deploy:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: 'android::Setup Java'
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - name: android::Configure Keystore
        run: |
          echo "$ANDROID_KEYSTORE_FILE" > keystore.jks.b64
          base64 -d -i keystore.jks.b64 > "android/app/$ANDROID_KEYSTORE_FILENAME"
          echo "storeFile=$ANDROID_KEYSTORE_FILENAME" >> keystore.properties
          echo "keyAlias=$ANDROID_KEYSTORE_ALIAS" >> keystore.properties
          echo "storePassword=$ANDROID_KEYSTORE_PASSWORD" >> keystore.properties
          echo "keyPassword=$ANDROID_KEYSTORE_KEY_PASSWORD" >> keystore.properties
        env:
          ANDROID_KEYSTORE_FILE: ${{ secrets.ANDROID_KEYSTORE_FILE }}
          ANDROID_KEYSTORE_ALIAS: ${{ secrets.ANDROID_KEYSTORE_ALIAS }}
          ANDROID_KEYSTORE_KEY_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_KEY_PASSWORD }}
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEYSTORE_FILENAME: ${{ secrets.ANDROID_KEYSTORE_FILENAME }}

      - name: android::Create Google Play Config file
        run : |
          echo "$ANDROID_PLAYSTORE_CONFIG_JSON" > play_config.json.b64
          base64 -d -i play_config.json.b64 > "android/$ANDROID_PLAYSTORE_CONFIG_JSON_FILENAME"
        env:
          ANDROID_PLAYSTORE_CONFIG_JSON: ${{ secrets.ANDROID_PLAYSTORE_CONFIG_JSON }}
          ANDROID_PLAYSTORE_CONFIG_JSON_FILENAME: ${{ secrets.ANDROID_PLAYSTORE_CONFIG_JSON_FILENAME }}
      
      - name: 'flutter build'
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.0.5'
      - run: flutter pub get
      #- run: flutter test
      - run: flutter build appbundle --release
      #- run: flutter build ios --release --no-codesign
      #- run: flutter build ipa
        env:
          ANDROID_KEYSTORE_FILE: ${{ secrets.ANDROID_KEYSTORE_FILE }}
          ANDROID_KEYSTORE_ALIAS: ${{ secrets.ANDROID_KEYSTORE_ALIAS }}
          ANDROID_KEYSTORE_KEY_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_KEY_PASSWORD }}
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEYSTORE_FILENAME: ${{ secrets.ANDROID_KEYSTORE_FILENAME }}

      
      - name: ios::Publish iOS Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: release-ios
          path: ios


      - name: android::Publish android Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: release-android
          path: build/app/outputs 


      - name: ios::Fastlane (archive, sign, upload to testflight) 
        uses: maierj/fastlane-action@v1.4.0
        with:
          lane: closed_beta
          subdirectory: ios
        env:
          APP_STORE_CONNECT_API_KEY_ISSUER_ID: '${{ secrets.APPSTORE_ISSUER_ID }}'
          APP_STORE_CONNECT_API_KEY_KEY_ID: '${{ secrets.APPSTORE_KEY_ID }}'
          APP_STORE_CONNECT_API_KEY_KEY: '${{ secrets.APPSTORE_PRIVATE_KEY }}'
          APP_APPLE_ID: '${{ secrets.APP_APPLE_ID }}'
          BUNDLE_ID: '${{ secrets.BUNDLE_ID }}'
          FASTLANE_APPLE_ID: '${{ secrets.APPLE_ID }}'
          MATCH_PASSWORD: '${{ secrets.MATCH_PASSWORD }}'
          GIT_AUTHORIZATION: '${{ secrets.GIT_AUTHORIZATION }}'
          PROVISIONING_PROFILE_SPECIFIER: '${{ secrets.PROVISIONING_PROFILE_SPECIFIER }}'
          TEMP_KEYCHAIN_PASSWORD: '${{ secrets.TEMP_KEYCHAIN_PASSWORD }}'
          TEMP_KEYCHAIN_USER: '${{ secrets.TEMP_KEYCHAIN_USER }}'

      
      - name: android::Fastlane (sign, upload to google play) 
        uses: maierj/fastlane-action@v1.4.0
        with:
          lane: closed_beta
          subdirectory: android
        env:
          ANDROID_KEYSTORE_FILE: ${{ secrets.ANDROID_KEYSTORE_FILE }}
          ANDROID_KEYSTORE_ALIAS: ${{ secrets.ANDROID_KEYSTORE_ALIAS }}
          ANDROID_KEYSTORE_KEY_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_KEY_PASSWORD }}
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEYSTORE_FILENAME: ${{ secrets.ANDROID_KEYSTORE_FILENAME }}
          ANDROID_PLAYSTORE_CONFIG_JSON_FILENAME: ${{ secrets.ANDROID_PLAYSTORE_CONFIG_JSON_FILENAME }}



    
